[package]
name = "nam"
authors = ["Mouhammed Nashat Helmi <Nashat.Helmi+Nam@Gmail.com>"]
license = "MIT"
version = "0.4.0-alpha"
edition = "2024"
publish = false

[dependencies]
color-eyre = "0.6.3"
nalgebra = "0.33.2"
reedline = "0.38.0"
