[package]
name = "nam"
authors = ["Mouhammed Nashat Helmi <KiN4Tec@Gmail.com>"]
license = "MIT"
version = "0.4.0-alpha"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0"
reedline = "0.41.0"
