[package]
name = "nam"
authors = ["Mouhammed Nashat Helmi <KiN4Tec@Gmail.com>"]
license = "MIT"
version = "0.4.0-alpha"
edition = "2024"
publish = false

[dependencies]
color-eyre = "0.6.5"
reedline = "0.41.0"
